config/routes.rb
Rails.application.routes.draw do

  get  '/search', to:'home#search'
  get  '/type', to:'profile#type'
  get  '/prof/:id', to:'profile#prof'
  get  '/profile/:id', to:'profile#index'

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  root 'home#index'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :confirmable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed

    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          image: auth.info.image,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20],
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def ensure_signup_complete
    # Ensure we don't go into an infinite loop
    return if action_name == 'finish_signup'

    # Redirect to the 'finish_signup' page if the user
    # email hasn't been verified yet
    if current_user && !current_user.email_verified?
      redirect_to finish_signup_path(current_user)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@users = User::where(tipo:2)
  	if user_signed_in?

  		user = User::find(current_user.id)
  		if user.tipo == nil
  			redirect_to type_path
  		end
  		
  	end
  end

  def search
  	@users = User::where(tipo:2)
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def self.provides_callback_for(provider)
    class_eval %Q{
      def #{provider}
        @user = User.find_for_oauth(env["omniauth.auth"], current_user)

        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
        else
          session["devise.#{provider}_data"] = env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end
    }
  end

  [:twitter, :facebook, :linked_in].each do |provider|
    provides_callback_for provider
  end

  def after_sign_in_path_for(resource)
    if resource.email_verified?
      super resource
    else
      finish_signup_path(resource)
    end
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
	def index
		@user = User::find(params[:id])
	end
	def type
	end

	def prof
		user = User::find(current_user.id)
		user.tipo = params[:id]
		user.save
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :finish_signup]

  # GET /users/:id.:format
  def show
    # authorize! :read, @user
  end

  # GET /users/:id/edit
  def edit
    # authorize! :update, @user
  end

  # PATCH/PUT /users/:id.:format
  def update
    #authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user 
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        @user.skip_reconfirmation!
        sign_in(@user, :bypass => true)
        redirect_to root_path, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
  
  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      accessible = [ :name, :email ] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def nav_link(link_text, link_path)
	  class_name = current_page?(link_path) ? 'active' : ''

	  content_tag(:li, :class => class_name) do
	    link_to link_text, link_path
	  end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/home/_lt.html.haml
%ul{:class=>'media-list'}
	-@users.each do |t|
		%li{:class=>'media'}
			.media-left
				
				%a{:href => "/profile/#{t.id}"}
					%img{:src => "#{t.image}?type=large",:style=>'width: 100px; height: 100px;' ,:class => "img-circle"}/
			.media-body
				%span{:class=>'badge bagde-online'} Online
				%h4{:class=>'media-heading'}= t.name
		
				.rank
					Rank:
					%i{:class=>"fa fa-star"}
					%i{:class=>"fa fa-star"}
					%i{:class=>"fa fa-star"}
					%i{:class=>"fa fa-star-half-o"}
					%i{:class=>"fa fa-star-o"}
					%span{:class=>'badge'}
						Teaches: Spanish
				%hr/
				%p
					Students Hello, I am a mathematician engineer and currently am dedicated to teaching Spanish.

app/views/home/index.html.haml
.jumbotron
	.container
		%h1 All The Teachers, All the Students, ONE PLACE
		%p I Want to Learn
		%p 
			%button{:class=>"btn btn-success btn-lg"} Suscribe Now!!

.container
	.row
		.col-md-12
			.text-center
				%h2 Find My Teacher

				%form{:action => "",:class=>'form-inline'}
					.form-group
						%label{:for => ""} Teachers Within
						= select(:email, :status, options_for_select([["5 KM", "1"], ["10 KM", "2"], ["25 KM", "3"]]))
					.form-group
						%label{:for => ""} Of
						= select(:email, :status, options_for_select([["Santiago", "1"], ["Providencia", "2"], ["Las Condes", "3"]]))

	%br/
	.row
		.col-md-6.col-md-offset-3
			.panel.panel-success
				.panel-body= render("lt")

app/views/home/search.html.haml
.container{:class=>"well"}
	.page-header
		%h1 
			Language
			%small I Want to Learn
	.row
		.col-md-12
		

			.col-md-5
				%h5 Where
				
				%form{:action => "",:class=>'form-inline'}
					.form-group
						%label{:for => ""}Teachers Within
						= select(:email, :status, options_for_select([["5 KM", "1"], ["10 KM", "2"], ["25 KM", "3"]]))
					.form-group
						%label{:for => ""} Of
						%input{:type => "text",:placeholder=>"You Address" ,:class=>'form-control'}/
				%div{:style=>'width:100%;height:335px;',:id=>'map'}
				%hr/
				%h5 When
				%lead My Schedule
			.col-md-7
				%h5 Filters
				%hr/
				= render "lt"


%script{:src=>'http://maps.googleapis.com/maps/api/js'}.
%script{:src=>'/js/marker.js'}
:javascript
	function initialize() {
		var center = new google.maps.LatLng(-33.4164703, -70.6028477);

		var map = new google.maps.Map(document.getElementById('map'), {
		zoom: 13,
		center: center,
			mapTypeId: google.maps.MapTypeId.ROADMAP
		});

		var markers = [];
	
		var latLng = new google.maps.LatLng(-33.4164703,-70.6028477);
		var marker = new google.maps.Marker({
			position: latLng
		});
		markers.push(marker);

		var latLng = new google.maps.LatLng(-33.4164342,-70.602959);
		var marker = new google.maps.Marker({
			position: latLng
		});
		markers.push(marker);
		
		var latLng = new google.maps.LatLng(-33.411901,-70.577908);
		var marker = new google.maps.Marker({
			position: latLng
		});
		markers.push(marker);

		var latLng = new google.maps.LatLng(-33.418145,-70.601353);
		var marker = new google.maps.Marker({
			position: latLng
		});
		markers.push(marker);


		var markerCluster = new MarkerClusterer(map, markers);
	}
	google.maps.event.addDomListener(window, 'load', initialize);

			

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>Nice to teach you</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
    <%= csrf_meta_tags %>

  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" style="padding-top: 3px;" href="/">
            <img src="/images/logo.jpg" alt="Nice to teach you" height="60px">
          </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <%= nav_link 'Home', root_path %>
            <%= nav_link 'Search', search_path %>
             <%= nav_link 'about', "///" %>
            <%= nav_link 'contact', "///" %>
 
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if(user_signed_in?) %>
              <li >
              <a href="" style="padding-top: 10px;padding-bottom: 15px;"><img src="<%= current_user.image %>" class="img-circle" style="height: 40px;"></a></li>
            <% else %>
              <li class="active"><%= link_to "Login", new_user_session_path%></li>
            <% end  %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

  
  <%=yield %>



  </body>
</html>

app/views/users/finish_signup.html.erb
<div id="add-email" class="container">
  <h1>Add Email</h1>
  <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
    <% if @show_errors && current_user.errors.any? %>
      <div id="error_explanation">
        <% current_user.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :email %>
      <div class="controls">
        <%= f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com' %>
        <p class="help-block">Please confirm your email address. No spam.</p>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Continue', :class => 'btn btn-primary' %>
    </div>
  <% end %>
</div>